language: android

env:
  global:
  - secure: TWlc4z+idiiNZS/STpyoPr6GdLVJMAYm2IgNfCqxOGvSenOqIIjVSsV1YFLBLgmK1+hDXUw7T3tqzmfiWWOyl/3UYvpMDzkd3I+fdR9+zLgFj92nnrrus+/Q1YY97OCKbs6lHrTowa92hLfoCBq2p7ij8m/iWi3oIw40zwe4zTPA4alJA7WfWBiGgDVQqb92++gH6eytMXlcRduOniFMdClvHmBInQgUF9NM9xoyv8Qddf2Iw89SGppBA32ljoEeVb1rE3MY99dFu2gXwiw7AskG6dIr3pTqFDDDPvx8lal2mQrwhHCp7t20GuKiYMbaxkYuLXsMuriS8IE6q8KV/lOSNhU7+fHDHS+jDJr37jnmmmUSeTfG+MFYIYPWlbmphkdAJetDk8jwILTXSGhJHQDAeVMc4TjfynWwmE7wCPoshXT3jwtnUB1FUpjpEe1vACGuOaRfAXHRVX0L1Q6+I3U91yRAiGiFZl7kIrAj3cyeAhU9jnG7bV4Z1zdx9Ke4oW5nimMOyibTicu+V13ataI9+cgHth7LWPw9VJaGGbr/rurcAsgB2wJ35g5/g/cTm4u3V2MqnGdjWKxo4aKVpBfpLLRlUYh5EU5Kl9+/ShVnF08iglvWF+fzrbhKyLKqCGSncHRFiPlLeQeS0tjAXfmqeFcKtx4M0VQByHqGGH8=
  - secure: VoY/zWE7itJmukAZt1Zw43jFzOk2ssWbpWhydYLiaRvplYVJvXTCSve4ZDpBhxPAlta2Kpfr9H8bwuaYCEtS+ovhi/q8Fo97YXiGdkHwEXJPal2n4O/XEj5hFr1BxIDTEwFBtGD/iQWZL/MVRaWFrfuMWajMZhDQkGz+DwRog4XCaw6UcEofW9kzfPG1T94C/bAIETrad4bfHKSbORVd2SbyPCFHkFH+YB/eWVqK2N5PuiPaet+EzcX/sxAFnwD6kF/uj3KxTlii/Yw8bM6LrPEWyyuMDglHN3LTevZ1CwT1oy8AUZaFzx246SL+Osn6t9WHoL1p3ltTS9O7sNL6WSyCP+JFYXF8iaF9USaINy/vcZFPsKdcCpgLPjSF/4mgXcjPc5KRao3tZOoamyvXuiGg7lfwUBl82t73ItlnSGgInAyUSesVrQ2gJNsVHdRqvOmVPBGXZ3lWb4GHksfQzLO210M7Tiu6leacWEbsYWmAsRER87qdUu7lY2b3wYJB7NhXX5AMZYINSzfCDVrThTWLXUU554D/3TmTKz/ROab2QxR/Qxh5i4ZJ/0MNdcM+qp8ORq6WlwGTUhCmD83XtiuBF3s/JW1WybsqC4Ppo23YuItqgfmMZWk75xLqpi48078vNgtEE/1YE2tvxd7ddfeT3eNLt7qrfj7Hu+r3L5A=

jdk:
- oraclejdk8

script: ./gradlew clean check --stacktrace

after_success:
- ./scripts/deploy_snapshot.sh

deploy:
  provider: script
  script: ./scripts/deploy_release.sh
  on:
    tags: true
    repo: aurae/android-junit5
