language: android

env:
  global:
  - secure: TWlc4z+idiiNZS/STpyoPr6GdLVJMAYm2IgNfCqxOGvSenOqIIjVSsV1YFLBLgmK1+hDXUw7T3tqzmfiWWOyl/3UYvpMDzkd3I+fdR9+zLgFj92nnrrus+/Q1YY97OCKbs6lHrTowa92hLfoCBq2p7ij8m/iWi3oIw40zwe4zTPA4alJA7WfWBiGgDVQqb92++gH6eytMXlcRduOniFMdClvHmBInQgUF9NM9xoyv8Qddf2Iw89SGppBA32ljoEeVb1rE3MY99dFu2gXwiw7AskG6dIr3pTqFDDDPvx8lal2mQrwhHCp7t20GuKiYMbaxkYuLXsMuriS8IE6q8KV/lOSNhU7+fHDHS+jDJr37jnmmmUSeTfG+MFYIYPWlbmphkdAJetDk8jwILTXSGhJHQDAeVMc4TjfynWwmE7wCPoshXT3jwtnUB1FUpjpEe1vACGuOaRfAXHRVX0L1Q6+I3U91yRAiGiFZl7kIrAj3cyeAhU9jnG7bV4Z1zdx9Ke4oW5nimMOyibTicu+V13ataI9+cgHth7LWPw9VJaGGbr/rurcAsgB2wJ35g5/g/cTm4u3V2MqnGdjWKxo4aKVpBfpLLRlUYh5EU5Kl9+/ShVnF08iglvWF+fzrbhKyLKqCGSncHRFiPlLeQeS0tjAXfmqeFcKtx4M0VQByHqGGH8=
  - secure: Uxvm+LtHvCHrmi4fZhN9QXv7M7y0Wkgx4iOiJzhLWgAHqprF1tBoe4Kw5U5oBqf5qxUpkDi7EH48rrcqPd+PEFr1DjR0fppQ/3+RvBa6IfUV2IbEyQdP8PXvE1eYWdeCVNUKVYuefurioiHgnCeMpYHp6aCmmeQVYeVlaohcNqumdPchndd2i5B7PHa0Ci9n8tRe9pBX85mANtfvwI+mj6ssoo6G5CIhGrLiP/4B0nx8JtT12UMTLiOKq/DOX3LkSvAjtsre/c6JC/eAhxjY3EQVdfGpTNInDFz7geLgiuZXb+9UrobMSR6PfPD1Y1Qh1J+H8Z8F9xHclQXbq2TFtFbk4xSDrZ3JIkFoHn8S6YyUx+AWrgIesTAA/D6YrSGX3z3uKQYoeJXnLAqdk9ysYPXPYS9ENq7vhSsaqrJiyjyiY6lmpyvzkyQ7Y6e+in2ch3kw/RHueoKnWnynnRbFNAhYbjegrAHY6Nxfdsw+2pPOn8TJxnlmzd/LXmLBVSP8dw1SosCVYx0RpvHvOINYTxxX51Pb5i9b7vp4Vr0vRQDjwThr2/Uo7mnwnx9HEBTrRJTc81VVFBGHZyT3Gv8aRCVu8nsJMmn19LbgYSpzNN44JqmiJ6B/5A+jIujBTKOoolVagK44/B4Zts5TYbdlqIBGbwUSmne1tLOQrCaK1Yg=

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.0
  - android-26
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository

jdk:
- oraclejdk8

script: ./gradlew clean check --stacktrace

after_success:
- ./scripts/deploy_snapshot.sh

deploy:
  provider: script
  script: ./scripts/deploy_release.sh
  on:
    tags: true
    repo: aurae/android-junit5
