# Shared default parameters and variables
defaults: &defaults
  working_directory: ~/root/project
  docker:
    - image: circleci/android:api-28-alpha
      environment:
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"'

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "plugin/android-junit5/build.gradle.kts" }}-{{ checksum "plugin/android-junit5-tests/build.gradle.kts" }}-{{ checksum "instrumentation/api/build.gradle.kts" }}-{{ checksum "instrumentation/runner/build.gradle.kts" }}-{{ checksum "instrumentation/sample/build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: (Plugin) Build
          command: cd plugin && ./gradlew :android-junit5:assemble --stacktrace --no-daemon
      - run:
          name: (Plugin) Test
          command: cd plugin && ./gradlew :android-junit5-tests:check --stacktrace --no-daemon
      
      - run:
          name: (Instrumentation) Download Dependencies
          command: cd instrumentation && ./gradlew androidDependencies --no-daemon
      - run:
          name: (Instrumentation) Build
          command: cd instrumentation && ./gradlew :api:assemble :core:assemble :runner:assemble --stacktrace --no-daemon
      - run:
          name: (Instrumentation) Test
          command: cd instrumentation && ./gradlew :api:check :core:check :runner:check --stacktrace --no-daemon

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - persist_to_workspace:
          root: ~/root
          paths:
            - project
      - store_artifacts:
          path: plugin/android-junit5-tests/build/reports/tests/test
          destination: plugin
      - store_artifacts:
          path: instrumentation/api/build/reports
          destination: instrumentation-api
      - store_artifacts:
          path: instrumentation/core/build/reports
          destination: instrumentation-core
      - store_artifacts:
          path: instrumentation/runner/build/reports
          destination: instrumentation-runner

  deploy_snapshots:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/root
      - restore_cache:
          <<: *cache_key
      - run:
          name: (Plugin) Deploy SNAPSHOTs
          command: cd plugin && ./gradlew publishLibraryPublicationToSnapshotRepository --stacktrace --no-daemon
      - run:
          name: (Instrumentation) Deploy SNAPSHOTs
          command: cd instrumentation && ./gradlew publishLibraryPublicationToSnapshotRepository --stacktrace --no-daemon

  deploy_plugin_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/root
      - restore_cache:
          <<: *cache_key
      - run:
          name: (Plugin) Deploy
          command: cd plugin && ./gradlew generatePomFileForLibraryPublication publish :android-junit5:bintrayUpload --stacktrace --no-daemon

#  deploy_instrumentation_release:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/root
#      - restore_cache:
#          <<: *cache_key
#      - run:
#          name: (Instrumentation) Deploy
#          command: cd instrumentation && ./gradlew generatePomFileForLibraryPublication publish :api:bintrayUpload :core:bintrayUpload :runner:bintrayUpload --stacktrace --no-daemon

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy_snapshots:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_plugin_release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: plugin-*
#      - deploy_instrumentation_release:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
#            tags:
#              only: instrumentation-*
