# Shared default parameters and variables
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/android:api-28-alpha
      environment:
        GRADLE_OPTS: '-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs="-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError"'

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "android-junit5/build.gradle" }}-{{ checksum "android-junit5-tests/build.gradle" }}-{{ checksum "instrumentation/build.gradle" }}-{{ checksum "instrumentation-runner/build.gradle" }}-{{ checksum "sample/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Build Plugin
          command: ./gradlew :android-junit5:assemble --stacktrace
      - run:
          name: Test Plugin
          command: ./gradlew :android-junit5-tests:check --stacktrace

      - run:
          name: Build Instrumentation
          command: ./gradlew :instrumentation:assemble :instrumentation-runner:assemble --stacktrace
      - run:
          name: Test Instrumentation
          command: ./gradlew :instrumentation:check :instrumentation-runner:check --stacktrace
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - persist_to_workspace:
          root: ~/project

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy plugin
          command: ls

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
            